### ISSUE TITLE
Instructions to run the repo

### ISSUE THREAD

**Issue by vidixha** [KushalRaut/Ethereum-Voting-App#29]
Can you please share the directions to run the repository? It would be a great help. Thanks in advance!

**Comment by KushalRaut** [comment]
To run the project:
1. Install and run ganache
2. Compile the smart contract with the help of the truffle framework
3. Make sure you get API access tokens and have them in .env file
4. Finally run the project after installing all the packages.

**Comment by vidixha** [comment]
Could you please tell me what are the dependencies to be installed in which folder? ( Elaborate instructions to run the project) please. Thank you!

**Comment by KushalRaut** [comment]
If you have basic knowledge of how truffle and React work for blockchain you should be able to run the code and the custom node server is built for other backend operations like login, authentication, etc.
